[package]
name = "boomerang"
version = "0.1.0"
edition = "2024"

# Cargo.toml 添加依赖
[dependencies]
polars = { version = "0.27", features = ["lazy"] }
ndarray-linalg = { version = "0.15", features = ["openblas"] }
ndarray = "0.15"